### PR TITLE
Modified timelimit for cluster/developing tracks

### PR DESCRIPTION
**Pull request by cedricclyburn**
Just minor edits to increase the length of timeout for tracks.

### CODE REVIEW

**Review by blues-man — CHANGES_REQUESTED** [review]
Please make the sum of all challenges timelimit between 1800 to 3000 seconds, better 1800 for such short labs

**Comment by cedricclyburn** [comment]
Sounds good @blues-man, timelimit has been updated!

**Review by blues-man — CHANGES_REQUESTED** [review]
I see 1800 for challenge, it's too much since it's 1800s * 4 = 120min!

**Comment by cedricclyburn** [comment]
Whoops @blues-man, just fixed 👍

**Review by blues-man — APPROVED** [review]
+1

**Pull request merged**
